import sys
sys.path.append("../")
from Individual import Supplier
from API_Database import insert_individual

supplier_data = """S	SHREE KUNJ BIHARI SAREES	SHREE K,B,	0
S	RAGHUPATI SAREES	RAGHUPATI	1
S	ASHOKA SELECTION PVT LTD	ASHOKA	2
S	SAI SARTHI ART	SAI SARTHI	3
S	SANGAM DESIGNER'S	SANGAM	4
S	SAMAY SAREES	SAMAY	5
S	SANGAM APPAREL'S	SANGAM A	6
S	ARTI CREATION	ARTI	7
S	NIKHAAR CREATIONS	NIKHAAR	10
S	TTARISH FASHIONS PVT LTD	TTARISH	11
S	DAAMAN IMPEX	DAAMAN	12
S	AADINATH SAREES	AADHINAT	13
S	AKSHITA BOUTIQUE	AKSHITA	16
S	AMEETA SAREES	AMEETA	17
S	SAI SATY SILK	SAI SATY	18
S	BHAGWATI FASHION	BHAGWATI	19
S	NIDDHI ENTERPRISES	NIDDHI	20
S	RANI TEXTILES	RANI	21
S	SAREE SANSAR	SAREE	22
S	SAINX TRENDZ	SAINX	23
S	KRISHNA FABRICS	KRISHNA FB	24
S	SONIYA INTERNATIONAL	SANIYA	25
S	SHIVAM TEX	SHIVAM TEX	26
S	AAKARSHAN	AAKARSHAN	27
S	KHAZANA SAREE HOUSE	KHAZANA	28
S	AASTHA CREATION	AASTHA	29
S	WAVELON FABRICS	WAVELON F	30
S	DOSHI DESIGNERS	DOSHI	31
S	KHUSHI TEXTILES PVT LTD	KHUSHI	32
S	SAROVAR BANDHANI	S BANDHANI	33
S	JIYA CREATION	JIYA	35
S	RAJGURU CREATIONS	RAJGURU	36
S	PARVATI FABRICS PVT LTD	PARVATI	37
S	JAY GANPATI	JAY GANPAT	39
S	J.J.GROUP OF MILLS	J.J.GROUP	40
S	DADIMA IMPEX	DADIMA IMP	41
S	BHAIRAV DESIGNER	BHAIRAV	42
S	RAGHUPATI NX	RAGHU NX	43
S	MUSKAN EXCLUSIVE	MUSKAN EX	44
S	MUSKAN PRINTS	MUSKAN	45
S	APARNA CREATION	APARNA	46
S	GANPATI	GANPATI	47
S	FLORAL CREATION	FLORAL	48
S	GIRIRAJ FASHION	GIRIRAJ	49
S	SURBHI SAREES	SURBHI	50
S	OM SHREE SYNTHETICS	OM SHREE	51
S	VENEZIA CREATIONS	VENEZIA	52
S	HI SELECTION FABRICS	 HI SELEC	53
S	PARIDHAN SILK MILLS	PARIDHAN	54
S	ANUSHKA SAREES	ANUSHKA	55
S	GANPATI SAREE	GANPATI	56
S	PALKI SAREES	PALKI	57
S	RISHABH FASHION	RISHABH F	58
S	EKTA PRINTS	EKTA	60
S	MANIDHARI FASHION	MANIDHARI	61
S	NE'O DESIGNERS	NE'O	62
S	VINEET CREATION	VINEET	63
S	VISHAL PRINTS	VISHAL	64
S	ARUSHI TEXTILS P LTD	ARUSHI	65
S	ANUSHKA FASHION	ANUSHKA	66
S	SIDHANT CREATIONS PVT LTD	SIDH CREAT	68
S	PUSHPA PRINTS	PUSHPA	69
S	DIVA'S	DIVA'S	70
S	B.R.SILK MILLS	B.R. SILK	71
S	SHRADDHA FABRICS	SHRADDHA	73
S	RATHOD TEXTILE WORLD	R TEX.WORL	74
S	RAGHUPATI TEXTILES	RAGHU TEX	75
S	KAPILA SAREE	KAPILA	76
S	ANKUR SAREES	ANKUR	77
S	DHRUVI CREATION	DHRUVI CRE	78
S	KAMDHENU CREATION	W	79
S	RADHE SILK MILLS	RADHE	80
S	SOHANPARI CREATION	SOHANPARI	81
S	MADHU PRIYA FASHION PVT LTD	M PRIYA FA	82
S	MOHAN INTERNATIONAL	MOHAN	83
S	VANASPATI CREATION P LTD	VANASPA C	84
S	GOPALA PRINTS	GOPALA	85
S	RASHI  DESIGNER	RASHI D	86
S	BALAJI SAREE (AASTHA CREATION)	BALAJI	87
S	SAJEELEE CREATION	SAJEELEE	89
S	ADITYA CREATION	ADITYA	90
S	SURIYA CREATION	SURIYA CRE	91
S	SAI DESIGNER CREATIVE	SAI DES CR	92
S	PRERANA SILK CORPORATION	PRERANA	93
S	VIBHOR SILK MILLS	VIBHOR	94
S	VANASPATI DESIGNER	V DESIGNER	95
S	ARHAM TEXTILES	ARHAM	96
S	S.N.SILK MILLS	S.N.SILK	97
S	SHREE KUNDAN PRINTS	KUNDAN	98
S	SWASTI SAREES	SWASTI SAR	99
S	SHREE HARI SAREE	S HARI SAR	100
S	RIDDHI SIDDHI FASHION	R S FASHIO	101
S	ONLY RAMJI CREATION	ONLY RAMJI	102
S	MANMOHAK FASHION	MANMOHAK	103
S	SHIVANS TRENDS	SHIVANS	104
S	NEW CREATION	NEW CREAT	106
S	RATNARAJ CREATION	RATNARAJ	107
S	JINNAM DRESS	JINNAM	108
S	WESTERN ART	WESTERN	109
S	SONA CHANDI TEXTILES	SONA	110
S	SIDHANT FABRICS	SIDH FABRI	111
S	MONARCH CREATIONS	MONARCH	112
S	JAY JAY TRANDZ PVT LTD	JAY TRANDZ	114
S	BHARGAVI CRATION	BHARGAVI	115
S	VINAYAK DESIGNER	VINAYAK DE	116
S	VLIKE CREATION	VLIKE CREN	117
S	RANGVARSHA SAREES	RANGVARSHA	118
S	TANVI CREATION	TANVI	119
S	SATISH SILK MILLS	SATISH SIL	120
S	JINRAJ SAREES	JINRAJ	121
S	RADHIKA SAREES (NEW)	RADHIKA NE	122
S	SHYAM FABRICS	SHYAM FAB	123
S	PIKASHO FASHION	PIKASHO	124
S	K.K.SILK MILLS	K.K.SILK	125
S	JAY SHREE FASHION	JAY SHREE	126
S	SULAKSHMI SAREES	SULKSHMI	127
S	NANDISH FASHION	NANDISH	128
S	PRAGYA FASHION	PRAGYA F	129
S	RADHIKA SAREES	RADHIKA	130
S	RACHIT FASHION PVT LTD	RACHIT	131
S	VRIDHI CREATION	VRIDHI	132
S	SHREE GOVERDHAN INTERNATIONAL	S GOVERDHN	133
S	MAHEK SAREES	MAHEK	134
S	ROZELLE SILK MILLS PVT LTD	ROZELLE	135
S	DIMPLE SAREES	DIMPLE	136
S	V.N.BANDHANI	V.N.BANDHA	137
S	SANGAM FASHION	SANGAM FA	138
S	SAI RAJ CREATION	SAI RAJ CR	139
S	AYAAN TRENDZ PVT LTD	AYAAN TRE	142
S	SILSILA SAREES	SILSILA	144
S	SHAMA CREATION	SHAMA	145
S	WAVLON SYNTHETICS	WAVLON	146
S	LUNIYA CREATION	LUNIYA	150
S	ARNAV SAREE	ARNAV	151
S	ASHIRWAD PRINT	ASHIRWAD	152
S	RIA FASHION HOUSE	RIA HOUSE	153
S	NIRAV FASHION	NIRAV	154
S	KRISHNA SAREES	KRISHNA	155
S	ROOP SHRINGAR	R SHRINGAR	156
S	SPARSH DESIGNER	SPARSH	157
S	SADBHAVNA FASHION	SADBHAVNA	158
S	SPARSH CREATION	SPARSH	159
S	GAYATRI ENTERPRISES	GAYATRI	160
S	FASHION STUDIO	F STUDIO	161
S	GAYATRI TEXTILES	GAYATRI T	162
S	PAVITRA SAACHI DESIGNER	PAVITRA	163
S	NEHA SILK MILLS	NEHA	164
S	CHECHANI SAREES PVT LTD	CHECHANI	165
S	NAYAN CREATION	NAYAN	166
S	SANSKRUTI SAREES	SANSKRUTI	167
S	GEETA PRINTS	GEETA	168
S	ROOP NIKHAR CREATION	ROOP	169
S	SHREE VINAYAK SAREES	VINAYAK	170
S	RAA SYNTHETICS	RAA	171
S	SAFFRON SAREES	SAFFRON	172
S	RINKI FASHION PVT LTD	RINKI	173
S	SHOURYA CREATION	SHOURYA	174
S	NAVAL CREATION	NAVAL	175
S	ANMOL SAREE	ANMOL	176
S	VANSHIKA CREATION	VANSHIKA	177
S	DEEPTI FASHION	DEEPTI	178
S	PARICHAY FASHION	PARICHAY	179
S	VISHAL NX	VISHAL NX	180
S	RATHOD SAREE EDITION	RATHOD	181
S	B.R.F.	B.R.F.	182
S	SHANKAR APPARELS PVT LTD	S.A.P.L.	183
S	JAY VIJAY PRINTS P LTD	JAY VIJAY	184
S	JANKI SILK MILLS	JANKI	185
S	B–3–SAREE	B–3	186
S	NANDANI CREATION	NANDANI C	187
S	SHREE ROOP RAJAT SAREE	ROOP RAJAT	188
S	GANPATI FASHION	GANPATI F.	189
S	RADHIKA CREATION	RADHIKA C	190
S	VINAYAK SAREES	VINAYAK	191
S	VIVAH ENTERPRISES	VIVAH	192
S	CHITRA FASHION	CHITRA	193
S	SMIT CREATION	SMIT	194
S	VANASPATI NX	VANASPATI	195
S	HIRAWAT FASHION	HIRAWAT	196
S	GOPAL SILK MILLS	GOPAL	197
S	ALLIANCE SAREES	ALLIANCE	198
S	GANPATI DESIGNER	GANPATI D	199
S	AVAVI ENTERPRISE	AVANI	200
S	VANASPATI SAREES	VANASPATI	201
S	MANSI CREATION (ANGEL)	MANSI	202
S	SUNDRAM FASHION	SUNDRAM	203
S	ANAND FABRICS	ANAND FAB	204
S	RAJGURU SAREES	RAJGURU	205
S	PANETAR SAREE HOUSE	PANETAR	206
S	SHUBHAM FASHION	SHUBHAM	207
S	RADHIKA FASHION	RADHIKA F	208
S	ANGEL SAREES	ANGEL S	209
S	KALPANA FASHION	KALPANA FA	210
S	SANSKRITI EMBROIDARY PVT LTD	SANS EMBO	211
S	SWARAA DESIGNER	SWARAA	212
S	VRNDAVAN SILK MILLS	VRANDAVAN	213
S	VIR BHADRA TEXTILES	VIR BHADRA	214
S	TAPASYA  FASHION	TAPASYA	215
S	VEER CREATIONS	VEER CREA	216
S	SHRI SAI CREATION	SHRI SAI C	217
S	VAIBHAV LAXMI CREATION	VAIBAHV L	218
S	VANASPATI CREATION	VANASPATIC	219
S	KISHORI FASHION	KISHORI	220
S	L.C.TEX	L.C.TEX	221
S	HIND POLY FASHION	HIND POLY	222
S	TANISHKA SAREES	TANISHKA	223
S	RADHIKA FAB.	RADHIKA F	224
S	MANJULA FASHION	MANJULA	225
S	UCHIT CREATION	UCHIT	226
S	UCHIT SAREES	UCHIT	227
S	YASH CREATION	YASH	228
S	YAMUNA PRINT	YAMUNA	229
S	SHREE HARI CREATION	HARI	230
S	YUVIKA SILK MILLS PVT LTD	YUVIKA	231
S	SHREE LAXMI VAR SAREES	LAXMI VAR	232
S	VANDANA SAREES	VANDANA	233
S	BANSURI FABRICS	BANSURI	234
S	LABH SILK MILLS	LABH	235
S	UCHIT TEXTILES	UCHIT TEX	236
S	MANSHVI SAREES	MANSHVI	237
S	SHREE BAJRANGFAB.	BAJRANG	238
S	SANJAY PRINTS	SANJAY	239
S	MAHAMAYA SAREES	MAHAMAYA	240
S	GADIA FABRICS	GADIA	241
S	SHUBHAM SILK MILLS	SHUBHAM	242
S	SURYAM CREATION	SURYAM	243
S	KALA SAGAR	KALA SAGAR	244
S	OM TEXTILES	OM TEX	245
S	RATAN PRIYA	RATAN PRIA	246
S	MANSI FASHION	MANSI	247
S	VANDAN SHREE TEX	VANDAN	248
S	AKASH SAREES	AKASH	249
S	ANTIQUE SAREES	ANTIQUE	250
S	PALAV FASHION	PALAV	251
S	VANSHIKAA BOUTIQUE	VANSHIKAA	252
S	DHANVARSHA SAREES	DHANVARSHA	253
S	GOPI TEXTILE	GOPI	254
S	MANAN FASHION	MANAN	255
S	VEDANSHI NX	VEDANSHI N	256
S	VEDANSHI CREATION P. LTD	VEDANSHI	257
S	GOVIND PRINT	GOVIND	258
S	AMBICA CRATION	AMBICA CRE	259
S	R.R.CREATION	R.R.CREATI	260
S	RISHABH INTERNATIONAL	RISHABH	261
S	MANMOHAK COLLECTION	MANMOHAK	262
S	VIOLET FASHION	VIOLET	263
S	OM ARTS	OM ARTS	264
S	PARI SAREES	PARI SAREE	265
S	PARGYA SAREES	PARGYA	266
S	KANYADAAN	KANYADAAN	267
S	MARUTI NX (SU)	MARUTI NX	268
S	M.D.SILK MILLS	M.D.SILK	269
S	NAVIN FASHION	NAVIN	270
S	SHREE GOVARDHAN SAREES	GOVARDHAN	271
S	HARIOM SILK MILLS	HARI OM	272
S	SHWETA DESIGNER SAREES	SHWETA	273
S	ROHIT TEXTILES	ROHIT	274
S	SIDDHI FASHION	SIDDHI	275
S	VIKALP SYNTHETICS	VIKALP	276
S	KRISHNAHARI FASHION PVT LTD	KRISHNA	277
S	KRISHNA HARI PRINTS	KRISHNA	278
S	SHRI SAI KRUPA CREATION P LTD	SHRI SAI	279
S	RADHESH DESIGNER PVT LTD	RADHESH	280
S	ADJSPRODUCT	ADJSPRODUT	281
S	WILSON PRINTS	WILSON	282
S	BANSAL SYNTHETICS	BANSAL	283
S	SUSHANT PRINTS	SUSHANT	284
S	SAGAR SYNTHETICS	SAGAR	285
S	V.M.TEXTILE	V.M.	286
S	JAY AMBE FAB.	JAY AMBE	287
S	OM SAI CREATION	OM SAI	288
S	J–S FASHION	J–S FASHIO	289
S	BHAKTI CREATION	BHAKTI	290
S	JAGDAMBA SILK MILLS	JAGDAMBA	291
S	SHIV PRIYA SAEES	SHIV PRIYA	292
S	SANKAT MOCHAN TEXTILES	SANKAT	293
S	SHRI KRISHANA TEXTILES	KRISHANA	294
S	AAYUSHI CREATION	AAYUSH	295
S	PRITI INTERNATIONAL	PRITI	296
S	MAHA MAYA TEX	MAHA MAYA	297
S	SURYA DESIGNERS	SURYA	298
S	MALVIKA SAREES	MALVIKA	299
S	BALAJI SILK MILLS (HIND)	BALA JI	300
S	SAI LEELA FAB.	SAI LEELA	301
S	RADHA ENTERPRISE	RADHA ENT.	302
S	SANTLAL TEKCHAND	SANTLAL	303
S	SIDHANT COLLECTIONS	SIDHANT CO	304
S	RANGUTSAV SAREES	RANGUTSAV	305
S	KANCHANA FASHIONS	KANCHANA	306
S	RAASHI CRATION	RAASHI	307
S	LAXMI SILK MILLS	LAXMI SILK	308
S	ROOP TARA FASHION	ROOP TARA	309
S	R.R.FASHION	R.R.FASHIN	310
S	SAI RAJ FAB.	SAI RAJ	311
S	PRATIKSHA FASHION	PRATIKSHA	312
S	RAGHUPATI CRATION	RAGHUPTI C	313
S	VISHWA SAREES	VISHWA	314
S	VEERMANI DESIGNER	VEERMANI	315
S	VEER DESIGNER	VEER DESIG	316
S	DREAM SILK MILLS PVT LTD	DREAM SILK	317
S	PBS PRINT	PBS PRINT	318
S	LAKME FASHION	LAKME	319
S	PRIYANKA PRINTS	PRIYANKA	320
S	SHREE MARUTI CREATION	MARUTI	321
S	KHUSHI SAREES	KHUSHI S	322
S	SAI MADHAV "NX"	MADAHV	323
S	SHRI SAI FASHION	SHRI SAI	324
S	MILAN FABRICS	MILAN	325
S	LAXMI RATNAKAR CREATION	LAXMIRATAN	326
S	SIDDHI CREATION	SIDDHI	327
S	VANASPATI TEX	VANAS TEX	328
S	VISHWAS SAREES	VISHWAS	329
S	SHREE ROOP SUKAN SAREE	ROOP SUKAN	330
S	SNEH SILK MILLS	SNEH	331
S	THAKURJI SILK MILLS	THAKURJI	332
S	BANSURI CREATION	BANSURI C	333
S	KALP FASHION	KALP FASH	334
S	PALLAV CREATION	PALLAV C	335
S	TISHA EXCLUSIVE	TISHA EX	336
S	M.D.SAREES	M.D.SAREES	337
S	DESIGNER'S	DESIGNER'S	338
S	TANYA FASHION	TANYA	339
S	VEER NX	VEER NX	340
S	RENUKA INTERNATIONAL	RENUKA	341
S	VIJAYANT CREATION	VIJAYANT	342
S	KAIA DESIGNER SAREES	KAIA DESIG	343
S	VIDHYA SYNTHETICS	VIDHYA	344
S	SUNDER ENTERPRISES	SUNDER	345
S	PRAPTEE DESIGNER	PRAPTEE	347
S	SARVIKA SAREES	SARVIKA	348
S	RAGHAV TEXTILE	RAGHAV	349
S	RATI CREATION	RATI	350
S	ANKIT SAREES	ANKIT	351
S	JAY JAY PRINT	JAY PRINT	353
S	ALFA FABRICS	ALFA FAB	354
S	SANJANA DESIGNER	SANJANA	355
S	VRANDAVAN SILK MILLS	VRANDAVAN	356
S	VIMLACHAL DESIGNER	VIMLACHAL	359
S	MEERA SILK MILLS	MEERA SILK	360
S	GOPIKA PRINTS	GOPIKA P	362
S	ANCHAL SAREE	ANCHAL S	363
S	GOPI SILK MILLS	GOPI SILK	364
S	SHIVANI COLLECTION	SHIVANI C	366
S	BABA RAJ FAB.	BABA RAJ	367
S	SAI TEX FAB	SAI TEX	368
S	SAI SABURI FAB.	SAI SABURI	369
S	SAROVAR SAREES	SAROVAR	370
S	VANASPATI PRINTS	VANASPATI	371
S	SAI TEX FAB SAREES PVT LTD	SAITEX FAB	372
S	SITA RAM CREATIVE	SITA RAM	373
S	SAI DEV TEXTILES	SAI DEV	374
S	VANSH PRINTS	VANSH	375
S	SAI MADHAV SAREES PVT LTD	MADHAV	376
S	SAI LONE	SAI LONE	377
S	BHARAT TXTILE MILLS	BHARAT	378
S	VIJAY RATAN CREATION	VIJAY RATA	379
S	SURBHI SYNTHETICS PVT LTD	SURBHI	380
S	LUNIYA DESIGNER	LUNIYA D	381
S	SHREE LAXMI CREATION	LAXMI	382
S	SANJAY SILK MILLS	SANJAY SIL	383
S	VIJAY SHREE CREATION	VIJAY SHRI	384
S	D.L.F.	D.L.F.	385
S	RAJDEEP CREATION	RAJDEEP	386
S	KAMAL TEXTILES	KAMAL	387
S	ROMA SILK MILLS	ROMA SILK	388
S	ZOOM FABRICS PVT LTD	ZOOM	389
S	VIVEK BANDHANI	VIVEK	390
S	VIVAH SYNTHETICS	VIVAH SYN	391
S	NAVRANG CREATION	NAVRANG	392
S	DEEP MANDIR SAREES	DEEP MANDR	393
S	RISHIKA FASHIONS P LTD	RISHIKA	394
S	SHRI MARU SILK MILLS P LTD	SHREE MARU	395
S	SAJEELEE (K)	SAJEELEE K	396
S	SANJANA DESIGNER SAREES	SANJANA	397
S	L.K.SONS	L.K.SONS	398
S	BALAJI PRINTS	BALAJI	399
S	AASTHA CREATION (K)	AASTHA(K)	400
S	RIDDHI SIDDHI CREATION	RIDDHI S	401
S	AMBAJI CREATION	AMBAJI	402
S	VIVAH FASHION	VIVAH FASH	403
S	SHYAM SAREES	SHYAM S	404
S	ZEENAT PRINTS P LTD	ZEENAT	405
S	NIHARIKA FASHION	NIHARIKA	406
S	RUHANI ALL SEASNS	RUHANI	407
S	SHAURYA FASHION	SHAURYA	408
S	PALAKH SAREES	PALAKH	409
S	NIRALI FASHION	NIRALI	410
S	SIDHANT SILK MILLS	SIDHANT SM	411
S	JAY SILK MILLS	JAY SILK	412
S	SHREE BALAJI FASHION	BALAJI FAS	413
S	SHEELALEKH SAREES	SHEELALEKH	414
S	VENUS DESIGNER	VENUS	415
S	ART DECOR FASHION PVT LTD	ART DECOR	416
S	SADBHAVNA CREATIONS	SADBHAVNA	417
S	S.T.F.	S.T.F.	418
S	INDIAN TEXTILE	INDIAN	419
S	VICKY CREATION	VICKY	420
S	ARNAV (K)	ARNAV (K)	421
S	R.J.D.	R.J.D.	422
S	SAMYAK SILK MILLS	SAMYAK	423
S	KRISHNA SAREE (NEW)	KRISHNA(N)	424
S	MADHU CREATION	MADHU	425
S	GARIMA SILK MILLS	GARIMA	426
S	MUSKAN SILK MILLS	MUSKAN	427
S	D.S.CREATION	D.S.CREATN	428
S	BRAHMANI FASHION	BRAHMANI	429
S	UMANG SILK MILLS	UMANG	430
S	MAHARANI SAREE	MAHARANI	431
S	PALAV SYNTHETICS PVT LTD	PALAV SYN	432
S	RIDDHI SIDDHI SAREES	R D SAREE	433
S	SHREE BALAJI CREATION	BALAJI CRE	434
S	VENICE CREATION	VENICE	435
S	ROHAN FABRICS	ROHAN FAB	436
S	JAY BALAJEE TEXTILES	JAY BALAJE	437
S	NIDHI FABRICS	NIDHI FAB	438
S	VINAYAK TEX	VINAYAK TE	439
S	SHRADDHA FASHION PVT LTD	SHRADDHA	440
S	ANKIT TEX	ANKIT TEX	441
S	MEGHA DESIGNER SAREES	MEGHA	442
S	MEERA FASHION	MEERA	443
S	PARAS CREATION	PARAS	444
S	PALAKH CREATION	PALAKH C	445
S	MUKTA DESIGNER	MUKTA DES	446
S	POONAM FASHION	POONAM FAS	447
S	KRISHNA TEXTILES	KRISHNA TE	448
S	SUNSILK CREATION	SUNSILK	449
S	SAI SHREEJI TEXTILES	SHREE JI	450
S	SHOBHA CREATION	SHOBHA C	451
S	SIDHANT SAREE PVT LTD	SIDH SAREE	452
S	SANWARIYA SAREES	SANWARIYA	453
S	SNEH SAREES	SNEH SAREE	454
S	DEEPSHIKHA CREATIVE NX	DEEPSHIKHA	455
S	GLORY SAREES	GLORY SARI	456
S	KANAIYA TEXTILES	KANAIYA TX	457
S	VEERJINESHWAR FASHIONS PVT LTD	VERJINESHR	458
S	SUNAKSHI SAREES	'SUNAKSHI	459
S	VIBHA CREATIONS	VIBHA CREA	460
S	NAVYA SAREES	NAVYA	461
S	VANYA DESIGNER	VANYA DES	462
S	MITTAL FASHION	MITTAL F	463
S	ROOP NIKHAR NX	R NKHAR NX	464
S	SHAILI	SHAILI	465
S	THE T9 COMPANY	THE T9 COM	466
S	MALISHKA FASHION	MALISHKA	467
S	GANPATI TEX	GANPATI TX	468
S	ANANYA SAREE	ANANYA	469
S	SUNEHARI NX	SUNEHARI	470
S	OMCO FASHION	ONCO	471
S	SHREE KRISHNA TEX	S KRISHNA	472
S	K.K.SONS	K.K.SONS	473
S	MARUDHAR KESHARI CREATON	MARUDHAR	474
S	DIVINE SAREES	DIVINE SAR	475
S	AMIPARA SILK MILLS	AMIPARA	476
S	ARTI FASHION	ARTI FASHN	477
S	PARIS CREATION PVT LTD	PARIS	478
S	K.K.INDUSTRIES	K.K.INDUS	479
S	VISAGAR POLY TEX LIMITED	VISAGAR	480
S	NEEL ENTERPRISES	NEEL	481
S	STREE	STREE	482
S	ANJALI PRINTS	ANJALI PRN	483
S	HEER NX	HEER NX	484
S	SHREE ROOP SUKAN CREATIONS	R S CREATN	485
S	RAGHUPATI SILKS	RAGHU SILK	486
S	V.SONS EMPORIO P LTD	V.SONS EMP	487
S	VIJAY DARSHAN SAREES	VIJAY DARS	488
S	RAVI TEXTILE	RAVI TEXTI	489
S	PALAKI PRINTS	PALAKI PRI	490
S	RADHIKA CREATION (NEW)	R CREATION	491
S	PRIYAL CREATION	PRIYAL CRE	492
S	TAANI SAREES P LTD	TAANI SARE	493
S	VITRAG PRINTS	VITRAG	494
S	SATVIK FASHION	SATVIK	495
S	SONAL SILK MILLS	SONAL SILK	496
S	SATYAM FASHION	SATYAM	497
S	GAMBHIR SILK MILLS	GAMBHIR	498
S	DIVYYA COLLECTION	DIVYYA	499
S	VIVAH CREATION	VIVAH CREA	500
S	DEEPIKA FABRICS	DEEPIKA FB	501
S	SHREE GANESH SAREES	S GANESH	502
S	NITIN SILK MILLS	NITIN SILK	503
S	GAJIWALA SAREES	GAJIWALA	504
S	B & D STUDIO PVT LTD	B&D STUDIO	505
S	TRIYA FASHION	TRIYA FAS	506
S	MAA KALI SYNTHETICS	MAA KALI	507
S	ASHIMA FASHION	ASHIMA FAS	508
S	PRIYAL FASHION	PRIYAL FAS	509
S	ASHIMA SAREE	ASHIMA SAR	510
S	SANGAM PRINTS	SANGAM PRI	511
S	KAMALA FASHION	KAMALA FAS	512
S	MONALISA TEXTILES	MONALISA	513
S	REVA FASHION	REVA	514
S	RAJLAXMI FASHION	RAJLAXMI	515
S	SAI TEXTILES	SAI TEXTIL	516
S	SHREE SAI SAREES	SHREE SA	517
S	TRIPATI FASHION	TRIPATI	518
S	B.L..SAREES	B.L.SAREES	519
S	SHRI SARVANAND TEX	SARVANAND	520
S	SHAMBHAV TEX	SHAMBHAV	521
S	B.L.PRINTS	B.L.PRINTS	522
S	SAANCHI SAREES	SAANCHI	523
S	WILSON ENTERPRISES	WILSON ENT	524
S	SAI DESIGNER	SAI DESIGR	525
S	SHREE BAJRANG FAB	BAJRANG	526
S	SUDARSHAN FASHION	SURDARSHAN	527
S	ROOP NIKHAR CREATION (K)	ROOP (K)	528
S	MAHALAXMI DESIGNER	MAHA L DES	529
S	JINRAJ	JINRAJ	530
S	DAKSHITA FASHION	DAKSHITA	531
S	TISHA PRINTS	TISHA PRIN	532
S	RIDDHI SIDDHI FASHION (K)	R SIDDHI K	533
S	KALISTA FASHION	KALISTA	534
S	APPLE SAREES PVT LTD	APPLE SARE	535
S	SAHIBA LIMITED	SAHIBA LTD	536
S	SURDARSHAN SAREES	SURDARS S	537
S	VERONICA DESIGNERS	VERONICA	538
S	RITVIKA CREATION	RITVIKA	539
S	VIJAY DARSHAN NX	VIJAY DARS	540
S	SHREYA DESIGNAR SAREES	SHREYA	541
S	S.N.PRINTS	S.N.PRINTS	542
S	PADMAVATI CREATION	PADMAVATI	543
S	JAMKUDI SAREES	JAMKUDI	544
S	JAY AMBE CREATION	JAY AMBE C	545
S	KANHAIYA PRINTS	KANHAIYA P	546
S	STUTI CREATION	STUTI CREA	547
S	BANSIDHAR CREATION	BANSIDHAR	548
S	SHREE CREATION	S CREATION	549
S	SHIV FABRICS	SHIV FABRC	550
S	SHRI SARVANAND FASHION	SHRI SARVA	551
S	C 4 U SAREES	C 4 U	552
S	KANAK LAXMI SAREES	KANAK LAXM	553
S	VIDHI VIDHAAN	VIDHI VIDH	554
S	TISHA SILK MILLS	TISHA SILK	555
S	RADHE SAI	RADHE SAI	556
S	SHRI SAI KRUPA CREATION (K)	SHRI SAI K	557
S	DIVINE FASHION CREATION P LTD	DIVINE FAS	558
S	KUSH SILK MILLS	KUSH SILK	559
S	ROOP LAXMI	ROOP LAXMI	560
S	SWARIT SAREES	SWARIT	561
S	RADHE KRISHNA FASHION	RADHE KRIS	562
S	GOKUL TEX	GOKUL TEX	563
S	PTC CREATIONS	PTC CREAT	564
S	DURGA FASHION	DURGA FAS	565
S	NAVKAR TEXTILE	NAVKAR	566
S	AMITA DESIGNER STUDIO	AMITA DESI	567
S	SAREE STUDIO	S STUDIO	568
S	FASHION DREAMS	FASH DREAM	569
S	LEHAR DESIGNER	LEHAR DES	570
S	SLOKA FASHION	SLOKA FASN	571
S	SAMBHAV SAREES	SAMBHAV S	572
S	ADINATH TEXTILES	ADINATH TX	573
S	NIKITA FASHION	NIKITA FAS	574
S	RAINBOW FASHIONS	RAINBOW	575
S	NAVYA DESIGNER	NAVYA DESI	576
S	SHREE MATESHWARI CREATIONS	MATESHWARI	577
S	VISHVAM DESIGNER	VISHVAM DE	578
S	MARUDHAR KESRI SAREES PVT LTD	MRUDHR SR	579
S	SHITAL COLLECTION	SHITAL COL	580
S	KALA SANGAM	KALA SANGA	581
S	SAMIKSHA DESIGNER	SAMIKSHA	582
S	ANOKHI SAREE	ANOKHI SAR	583
S	ADESHWAR TEXTILES	ADESHWAR	584
S	SHREE NATH JI FABRICS	NATH FABRC	585
S	KASHISH CREATION	KASHISH C.	586
S	LAXMI MANI SAREES	LAXMI MANI	587
S	RAAS LILA DESIGNAR	RAAS LILA	588
S	SHREE HARI FASHION STUDIO	H F STUDIO	589
S	RAJAT CREATION	RAJAT C	590
S	ARADHYA SAREES]	ARADHYA S	591
S	MILTON FAB	MILTON FAB	592
S	HITESH NX	HITESH NX	593
S	VIMLACHAL CREATION	VIMLACHALC	594
S	SIDHANT CREATION (K)	SIDHANT K	595
S	EAST INDIA FASHION	EAST INDIA	596
S	SIDDHI TEXTILES	SIDDHI TEX	597
S	SHIV SAVITRI CREATION	S SAVITRI	598
S	RIA SAREE	RIA SAREE	599
S	RANGUTSAV DESIGN	RANGUTSA D	600
S	PARUL TEXTILE	PARUL TEX	601
S	GOPAL FASHION	GOPAL FAS	602
S	ADARSH TEXTILES	ADARSH TEX	603
S	KRISHNAM	KRISHNAM	604
S	THAVKI SAREES PVT LTD	THAVKI SAR	605
S	VITRAG DESIGNER	VITRAG DES	606
S	VIJAY TRADERS	VIJAY TRAD	607
S	SHREE V.L.DESIGNER	V.L.DESIGN	608
S	KALA NIKETAN SAREES	KALA NIKTN	609
S	B.K.SILKS MILLS PVT LTD	B.K.SILKS	610
S	HEER DESIGNER	HEER DESIG	611
S	USHA NISHA FASHION	USHA NISHA	612
S	KANAK SILK MILLS	KANAK SILK	613
S	KANAK FASHION	KANAK FASH	614
S	S.K.SAREES	S.K.SAREE	615
S	EAST INDIA SAREES	EAST SAREE	616
S	WHATSUP FASHION	WHATSUP	617
S	JAIPUR SYNTHETICS	JAIPUR SYN	618
S	SHREE GURU FASHION	S GURU FAS	619
S	SHREE KRISHNA CREATION	S KRISHNA	620
S	NAVKAR CREATION	NAVKAR C	621
S	ASTHA SYNTHETICS	ASTHA SYN	622
S	SAI NX	SAI NX	623
S	9 NX DESIGNER	9 NX DESIG	624
S	VIDEET CORPORATION	VIDEET COP	625
S	YASH SAREE	YASH SAREE	626
S	SAMBHAV PRINTS	SAMBHAV P	627
S	KESSI FABRICS PVT LTD	KESSI F P	628
S	VITRAG FAB	VITRAG FAB	629
S	AMBIKA RAAS	AMBIKA RAA	630
S	SIDHANT SAREES PVT LTD 1	S SAREE 1	631
S	SOHANPARI (K)	SOHNPRI K	632
S	SONI FASHION	SONI FASHN	633
S	NAVAL DESIGNER	NAVAL DES	634
S	MANISHA SAREES	MANISHA S	635
S	VIJAY DARSHAN PRINTS	V D PRINTS	636
S	MAHA LAXMI DESIGNER	MAHA L DES	637
S	ABHINANDAN CREATION	ABHINANDAN	638
S	MANISHA CREATION	MANISHA C	639
S	SANCHI SAREES	SANCHI S	640
S	SANSKRUTI	SANSKRUTI	641
S	PIKASHO DESIGNER	PIKASHO D	642
S	SATAKSHI DESIGNER SAREES	SATAKSHI D	643
S	NEMTARA FASHION	NEMTARA F	644
S	DWARKANATH DESIGNER	DWARKA DE	645
S	UTSAV SAREES	UTSAV SAR	646
S	B FRESH SAREES	B FRESH	647
S	KANAK CREATION	KANAK CRE	648
S	JAY VEER CREATION	JAY VEER C	649
S	SHREE SWAGAT SILK	SWAGATSILK	650
S	RIDDHI SUMAN FBRICS	R SUMAN FB	651
S	SENSE	SENSE	652
S	TANUSHREE FASHION	TANUSHREE	653
S	LAVANYA	LAVANYA	654
S	OKAY SILK MILLS	OKAY SILK	655
S	TANISHKAA CREATION	TANISH CRA	656
S	PARAS IMPEX	PARAS IMP	657
S	GADIA FASHION	GADIA FAS	658
S	GAYATRI CREATION	GAYTRI CRE	659
S	SURDARSHAN FASHION	SURDAR FAS	660
S	SUMANGAL SAREE	SUMANGAL	661
S	SHREE RANG TRNDZ VT LTD	RANG TRNDZ	662
S	OM ADITYA IMPEX	OM ADITYA	663
S	NISCHAY CREATION	NISCHAY C	664
S	SHIVAM EXPORTS	SHIVAM EXP	665
S	SARTHAK SAREES PVT LTD	SARTHAK S	666
S	SONI DESIGNER	SONI DESI	667
S	VIDHYA SAREES	VIDHYA S	668
S	PRATIBIMB FASHIONS PVT LTD	PRATIBIMB	669
S	T.BLUE SAREES	T.BLUE SAR	670
S	RAVIRAJ SAREES PVT LTD	RVIRAJ S	671
S	BANSI FASHION PVT LTD	BANSI FASH	672
S	DUPATTA HOUSE	DUPATTA H	673
S	ANOKHI DESIGNER	ANOKHI DES	674
S	JINKUSHAL SAREES	JINKUSHAL	675
S	SHANAYA ETHNIC FASHION	SHANAYA	676
S	AMAR SAREES	AMAR SAREE	677
S	MUKTA ENTERPRISES	MUKTA ENT	678
S	VITRANG SILKS	VITRANG S	679
S	SUBH CRETION	SUBH CRE	680
S	LIFE STYLE SAREES PVT LTD	LIFE STYLE	681
S	GAVLEE 999	GAVLEE 999	682
S	LAXMI NARAYAN TEXTILE	LAXMI NAR	683
S	KAMDHENU FASHION	KAMDHENU	684
S	KAJREE FASHIN	KAJREE FAS	685
S	SHRADDHA PRINTS	SHRADDHA P	686
S	RACHNA ART PRINTS PVT LTD	RACHNA ART	687
S	RESHMA SAREE	RESHMA SAR	688
S	TANVI DESIGNER	TENVI DES	689
S	VEERANA NX	VEERANA NX	690
S	SAROVAR TEXTILES	SAROVAR T	691
S	SHREE BALAJI TEXCO	S BALAJI T	692
S	TULSI FASHION	TULSI FAS	693
S	SHREE KRISHNA SAREES	KRISHNA S	694
S	ANJANI CREATION	ANJANI CRE	695
S	PRATHAM SAREE	PRATHAM S	696
S	MANU FASHIONS PVT LTD	MANU FASH	698
S	MAHA MITRA CREATIONS	MAHA MITRA	699
S	NIRVANA	NIRVANA	700
S	SANSKAR TEX PRINT	SANSKAR	701
S	MAHI ENTERPRISES	MAHI ENTER	702
S	SHRI GANPATI SAREES	S GANPATI	703
S	S&K ENTERPRISES	S&K ENTER	704
S	SARIKA FASHION	SARIKA FAS	705
S	PARCHAAI	PARCHAAI	706
S	ADI CREATION	ADI CREATN	707
S	APURVA SHREE	APURVA S	708
S	RANGOLI CAREATION	RANG	709
S	SIMONI PRINTS	SIMONI	710
S	VITRAG TEX	VITRAG	711
S	SUN CRATION	SUN CRE	712
S	RAJ KUNVAR FASHION	RAJKUNVAR	713
S	LIRIL FASHION	LIRIL F	714
S	PINTU SAREES	PINTU S	715
S	SANGEET CREATION	SANGEET C	716
S	RUCHI SAREES	RUCHI S	717
S	K.K.EXCLUSIVE	K.K.EXCLUV	718
S	SANSKRUTI SILKS MILLS PVT LTD	SANSKRUTIS	719
S	UNNATI FASHION	UNNATI F	720
S	CLASSIC DESIGNERS	CLASSIC D	721
S	KHAITAN INDIA SILKS MILLS	KHAITAN IN	722
S	ABHINANDAN TEXTILES	ABHINANDAN	723
S	KALPATARU TEXTILES	KALPATARU	724
S	MOHIT PRINTS	MOHIT P	725
S	ABHINANDAN FASHION	ABHINANDAN	726
S	HITANSH FASHION	HITANSH F	727
S	L.V.SAREES	L. V.SAREE	728
S	WAAHDIL FASHION	WAAHDIL F	729
S	KANAK SILK MILLS (VIJAY DARSH)	K S M	730
S	MONIKA PRINTS P.LTD	MONIKA  P.	731
S	NAMO COMPANY	NAMO CO.	732
S	PRIT FASHION	PRIT FASHN	733
S	KRISHNA FAB(HITESH NX)	KRISHNA  F	734
S	ANJALI FASHION	ANJALI F.	735
S	MONALI DESIGNER	MONALI D	736
S	SOHAN ART	SOHAN ART	737
S	THAKUR DESIGNER	THAKUR D	738
S	MANOHAR ARTS	MANOHAR A	739
S	RISHI RAJ SAREES	RISHI RAJS	740
S	RAGHUPATI COLLECTION	RAGHUPATI	741
S	KALM KARI	KALM KARI	742
S	DADUVAANI FASHION	DADUVAANI	743
S	9–UP CREATION	9–UP C..	744
S	KRISH FASHION	KRISH FASH	745
S	VEER HANUMAN CREATION	V. H. C	746
S	SUBHA CREATION	SUBHA C..	747
S	GINNI FASHION	GINNI FASH	748
S	KANCHAN SILK MILLS	KANCHAN S	749
S	VIJAY DARSHAN TEXTILES	V.D.T.	750
S	VIJAY DARSHAN SILKS	V.D.S.	751
S	V.TEX	V.TEX	752
S	APURVA FASHION	APURVA F	753
S	ANJALI FASHION 2	ANJALI F.2	754
S	SHIV SHAKTI SAREES	SHIV SHAKT	755
S	G.M.SILK MILLS	G.M.SILK M	756
S	KIMORA FASHION P. LTD	KIMORA F.	757
S	KHATU SHREE SAREES	KHATU S.	758
S	KARISHMA PRINTS	KARISHMA P	759
S	VIRATRA DESIGNER	VIRATRA D.	760
S	DEEPIKA FASHION	DEEPIKA F.	761
S	TULSI SAREES	TULSI S.	762
S	NAVYA TRENDZ	NAVYA T.	763
S	SAI DESIGNER FAB	SAI D.F.	764
S	AADINATH CREATION	AADINATH C	765
S	SAI SWARNA	SAI SWARNA	766
S	ATMA VALLABH DESIGNER	A.V.D	767
S	L. JINESH&CO.(WHATSUP)	L.JINESH	768
S	BEEKY&CO.	BEEKY&CO.	769
S	PAVITRA	PAVITRA	770
S	MANTHAN CREATIONS P.LTD	M.C.P.L.	771
S	MAHOTSAV CREATION P.LTD	MAHOTSAV	772
S	KHODIYAR FASHION	KHODIYAR F	773
S	DHANUSHRI DESIGNER	DHANUSHRI	774
S	V.RAJ GOPI CREATION	V.RAJ G.C.	775
S	SPARKLE EXPORT	SPARKLE E.	776
S	POLKA	POLKA	777
S	SHREE HARSIDDHI FASHION	SHREE H.F.	778
S	SHANGRILA CREATION	SHANGRILAC	779
S	KARIGARI	KARIGARI	780
S	BINDIA PRINTS	BINDIA P.	781
S	SHEETAL SILK MILLS	SHEETALSM.	782
S	SWANSHRI CREATION	SWANSHRI C	783
S	SIDDHI VINAYAK KNOTS&PRINTSP.L	S.V.K&P.PL	784
S	VIJAY SHREE FASHION	V.S.F.	785
S	TOP CHOICE FASHION	T.C.F.	786
S	BAHURANI	BAHURANI	787
S	NANDAN NX	NANDAN NX	788
S	ANJANI FASHION	ANJANI F.	789
S	VISHAL EXCLUSIVE	VISHAL EXU	790
S	SHREENATH FASHION	SHREE N. F	791
S	KANAN CREATION	KANAN C.	792
S	R.S. CREATION	R.S. CRE.	793
S	ZIRR	ZIRR	794
S	SHIV MAHADEV	SHIV MAHA	795
S	S.K.P.DESIGNER	S.K.P.DE.	796
S	ATAL CREATION	ATAL C.	797
S	LAVISH RAKESH &CO.	L.R.&CO.	798
S	VANS CREATION	VANS C.	799
S	SASYA DESIGNER	SASYA D.	800
S	SHREE VAISHALI	SHREE V.	801
S	MISHIKAA DESIGNER	MISHIKAA D	802
S	MANISH CREATION	MANISH C.	803
S	PARINEETA SAREES	PARINEETA	804
S	PEE DESIGNER	PEE D.	805
S	KALASH CREATION	KALASH C.	806
S	TARUN FASHION P.LTD	TARUN FASH	807
S	MANISH SALES CORPORATION	M.S.C.	808
S	SAI LADLI DESIGNER	S.L.D.	809
S	KHATU SHYAM SILK MILLS	K.S.S.M.	810
S	APURVA DESIGNER	APURVA D.	811
S	PAYAL SAREE	PAYAL SARE	812
S	RUDRAKSH FASHION	RUDRAKSH	813
S	SHANGRILA FASHION	SHANGRILA	814
S	TARUN SILK MILLS	TARUN S.M.	815
S	PEARL DESIGNER	PEARL D.	816
S	SIX YARD	SIX YARD	817
S	AMBER CREATION	AMBER C.	818
S	PANGHAT CREATION	PANGHAT C.	819
S	JINENDRA SAREES	JINENDRA S	820
S	VICHAKSHAM SHREE SAREES	V.S.S.	821
S	PARIS DESIGNER	PARIS DE.	822
S	KRISHNA FASHION	KRISHNA F.	823
S	ROOP RAJAT CREATION	ROOP RAJAT	824
S	SHREE GANPATI SAREES	S.G.S.	825
S	GUNJAN SILK MILLS	GUNJAN S.M	826
S	RAJ FASHION	RAJ FASHIO	827
S	VALCHAND&SONS	VALCHAND	828
S	CHANDANI CREATION	CHANDANI	829
S	ADESHWER DESIGNER	ADESHWER	830
S	RAAS CREATION	RAAS C.	831
S	RADHA TEX	RADHA TEX	832
S	SIDDH TEXTILES	SIDDH T.	833
S	SHUBH TREND	SHUBH TREN	834
S	B.JINESH&CO.	B.JINESH	835
S	EKTA INTERNATIONAL	EKTA INTER	836
S	VRINDAVAN TEXTILES	VRINDAVAN	837
S	KAIA	KAIA	838
S	SIMARAN FASHION	SIMRAN FAS	839
S	MONALISA	MONALISA	840
S	MILTION FASHION	MILTION FA	841
S	PANCHHI FASHION	PANCHHI F.	842
S	SHEETAL CREATION	SHEETAL C.	843
S	KISHORI	KISHORI	844
S	VEER VANDAN CREATION	VEER VANDN	845
S	SHEETAL FASHIONS	SHEETAL F.	846
S	ROOPAM SILK MILLS	ROOPAM S	847
S	S.DEV FASHION	S.DEV F.	848
S	LAJO DRESS MATERIAL	LAJO D.M.	849
S	VANSHIKAA TEXTILES	VANSHIKAA	850
S	AISH CREATION	AISH CREA	851
S	SHITAL DESIGNER	SHITALN D.	852
S	SHREE GANESHLAXMI FABRICS	S.G.F.	853
S	RANGOLI SILK MILLS	RANGOLI SM	854
S	KALPVRISH SAREES	KALPVRISH	855
S	DESILUK FASION P.LTD	DESILUK F.	856
S	7 BEAUTY SAREES	7 BEAUTY S	857
S	VATSALYA CREATION	VATSALYA C	858
S	INDIAN FASHION	INDIAN F.	859
S	ELITA CREATION	ELITA C.	860
S	AARYA FASHION	AARYA F.	861
S	SAGAR TEXTILES	SAGAR TEXT	862
S	KRISHANM CREATION	KRISHANM C	863
S	SHIV SANDHYA	SHIV SANDA	864
S	KAMIYA LIFESTYLE	KAMIYA L.S	865
S	NANDITA	NANDITA	866
S	YATHARTH CREATION	YATHARTH C	867
S	S.R.DESIGNER	S.R.DESIGR	868
S	MAHAK TEXTILES	MAHAK TEX.	869
S	MEHTA N MEHTA	MEHTA N M.	870
S	ROMSHAY FABRICS	ROMSHAY F.	871
S	SOCH	SOCH	872
S	PANIHARI FASHION	PANIHARI F	873
S	NANDLAL DESIGNER	NANDLAL D.	875
S	VIVILS SILK MILLS P.LTD	VIVILS S.M	876
S	RAJESHWER NX	RAJESHWER	877
S	LATEST CREATION	LATEST C.	878
S	SANJOLI SAREE	SANJOLI S.	879
S	KIRAN SHREE FASHION	KIRAN S.F.	880
S	IMPACT FASHION	IMPACT F.	881
S	ARIHANT TEXTILES	ARIHANT T.	882
S	VRAJ GOPI DESIGNER	VRAJGIPI D	883
S	MEET CREATION	MEET CRE..	884
S	MADHURAM SAREES	MADHURAM	885
S	MANIYAR SYNTHETICS P.LTD	M.S.P.L.	886
S	AHINSA  CREATION	AHINSA C.	887
S	BHAGWATI CREATION	BHAGWATI C	888
S	LAXMI HARI PRINTS P.LTD	L.H.P.P.L.	889
S	MANASI SAREES P.LTD	M.S.P.L.	890
S	SHANGRILA DESIGNER	SHANGRILA	891
S	SUNNY SILK CORPORATION	S.S.C.	892
S	SUBHASH SAREES P.LTD	SUBHASH S.	893
S	AVENUE CREATION	AVENUE C.	894
S	MAISHAA SAREES	MAISHAA S.	895
S	KESARI NANDAN	KESARI N.	896
S	SAJANI SILK MILLS	SAJANI S.M	897
S	MAGGY FASHION	MAGGY F.	898
S	ACHERA DESIGNER	ACHERA D.	899
S	JAY SHREE SAGAR CREATION	J.S.S.C.	900
S	VANILLA SAREES	VANILLA S.	901
S	JAY AMBE SAREES	JAY AMBE S	902
S	AKRUTI ART	AKRUTI ART	903
S	VASTRAM SAREES	VASTRAM S.	904
S	SHREE NEELKANTH SAREES	S.N.K.S.	905
S	MANSI SYNTHETICS	MANSI S.	906
S	SWASTIK FASHION	SWASTIK F.	907
S	PURNIMA PRINTS	PURNIMA P.	908
S	ANTRA CREATION	ANTRA CRE.	909
S	V.S. DESIGNER	V.S.DESIGR	910
S	SHANTI NX	SHANTI NX	911
S	SHRI HARI FASHION	SR HARI F.	912
S	DIPAK SAREES	DIPAK SARE	913
S	NAVYAM	NAVYAM	914
S	VANIVATSALYA SAREES	VANIVATSAL	915
S	V.KUSHAL	V.KUSHAL	916
S	SHIPRA DESIGNER	SHIPRA D.	917
S	SHUBHKARI CREATION	SHUBHKARI	918
S	V–3 DESIGNER	V–3 DESIGR	919
S	NEEL MADHAV CREATION	NEEL M.C.	920
S	MANISH INTERNATIONAL	MANISH IN.	921
S	ADITI FASHION	ADITI F.	922
S	HIRAL CREATION	HIRAL C.	923
S	PRIYA PARIDHI SAREES	PRIYA P.S.	924
S	TARRAH FASHION LLP	TARRAH F.L	925
S	TIMES FASHION	TIMESF	926
S	JAY AMBEY SILK	JAY AMBEY	927
S	JAY AMBEY FASHION	JAY AMBE F	928
S	NARAYAN SILK MILLS	NARAYAN S.	929
S	VANSHPRIYA FASHION	VANSPRIYA	930
S	GAUTAM FASHION	GAUTAM F.	931
S	ROOP RAJAT SAREES	ROOP RAJAT	932
S	DEEPANSHI CREATION	DEEPANSHIC	933
S	MAYA FASHION	MAYA FASHN	934
S	KRISH CREATION	KRISH C.	935
S	ABHISHEK CREATION	ABHISHEK C	936
S	MASKARI TRENDZ	MASKARI TR	937
S	S–3 DESIGNERS	S–3DESIGNR	938
S	TATHASTU	TATHASTU	939
S	HETANSHI	HETANSHI	940
S	AMBER SAREES	AMBER SARE	941
S	ALOISE SAREES P.LTD	ALOISE S.	942
S	SATVACHAN	SATVACHAN	943
S	SHREE LAXMI NARAYAN SYNTHETICS	S.L.N.S.P.	944
S	REKHA PRINTS	REKHA P.	945
S	KAJOL CREATION	KAJOL CRE.	946
S	SANVI FASHION	SANVI FASH	947
S	SHAILLY  INTERNATIONAL	SHAILLY IN	948
S	SHREE FASHION	SHREE FAS	949
S	AARA TRENDZ	AARA TRENZ	950
S	KAVERI SILAK MILLS (P) LTD	KAVERI S.M	951
S	PALAK FASHIONS	PALAK FAS	952
S	AADHYANA FASHION	AADHYANA	953
S	SAWARI SAREE	SAWARI S.	954
S	NATRAJ SILK MILLS	NATRAJ S.	955
S	SHUBH LAXMI FASHION	SHUBH L.F	956
S	KOHINOOR TEXTILES	KOHINOOR T	957
S	PRAGATI FASHION	PRAGATI F.	958
S	ANANYA CREATION	ANANYA C.	960
S	MADHAV CREATION	MADHAV C.	961
S	MAJITHIYA FASHION	MAJITHIYA	962
S	SHREE RAM CREATION	SHREE RAM	963
S	DHANLAXMI TEXCO FAB PVT LTD	D.L.T.F.P.	964
S	V.STUDIO FASHION	V.STUDIO	965
S	MAMTA DESIGNER	MAMTA D.	966
S	AABHA CREATION	AABHA C..	967
S	RADHE MADHAV	RADHE MADV	968
S	KUSHAL	KUSHAL	969
S	PUNYAH FASHION	PUNYAH F.	970
S	RUDRA CREATION	RUDRA C.	971
S	SURUCHI SAREES	SURUCHI S.	972
S	KARNI TEXTILE AGENCY	KARNI TEX	973
S	KANVI FASHION	KANVI FASH	974
S	CHINTAMANI SAREES	CHINTAMANI	975
S	SASUMA CREATION	SASUMA C.	976
S	SHITAL NX	SHITAL NX	977
S	HARIPRIYA	HARIPRIYA	978
S	MAHADEV LIFE STYLE	MAHADEV L.	979
S	PARSHVANATH	PARSHVNATH	980
S	SHIV SHAKTI CREATION	SHIV SHAKI	981
S	VASTREENI	VASTREENI	982
S	J.S.S.B.WORLD	J.S.S.B.WO	983
S	NARAYAN TEXTILES	NARAYAN T.	984
S	KARNI	KARNI	985
S	NAVNIDHI PRINTS	NAVNIDHI P	986
S	VRAJ GOKUL	VRAJ GOKUL	987
S	CHAKACHAK TEXTILES	CHAKACHAK	988
S	M.K. TEXTILES	M.K.TEX..	989
S	SALASAR CREATION	SALASAR C	990
S	BIYAH	BIYAH	991
S	AVADHI FASHIONS	AVADHI FAI	992
S	AMAYA FABRICS P.LTD	AMAYA FAB.	993
S	VAANI CREATION	VAANI CRE.	994
S	LAJAS CREATION	LAJAS CREA	995
S	PARINEETA EXCLUSIVE	PARINEETA	996
S	SAVARNA CREATION	SAVARNA C.	997
S	SHREE RAJ LAXMI TEXTILE	S.R.L.T.	998
S	KARNI FASHION	KARNI F.	999
S	WOMEN STYIE	WOMEN STY	1000
S	DEV GUMNI TEXTILES	DEV GUMNI	1001
S	MANISH NX	MANISH NX	1002
S	KRISHNA DESIGNER	KRISHNA DG	1003
S	SAI KABRA DESIGNER	SAI KABRA	1004
S	SIDDHA LAXMI FASHION	SIDDHA L.F	1005
S	SHILP KALA FASHION P.LTD	SHILP KALA	1006
S	WELCOME SAREES	WELCOME S	1007
S	RANISHA CREATION	RANISHA C.	1008
S	ANAND SAREES	ANAND SARE	1009
S	GAURI CREATION	GAURI C.	1010
S	DEEPMALA SAREES	DEEPMALA	1011
S	GEETA SILK MILLS	GEETA S.M.	1012
S	VIBHUTI CREATION	VIBHUTI C.	1013
S	MAHADEV CREATION	MAHADEV C	1014
S	BHIM NATH CREATION	BHIMNATH C	1015
S	AMIDHARA CREATION	AMIDHARA C	1016
S	NAKODA TEXTILES	NAKODA T.	1017
S	LAKSH CREATION	LAKSH C.	1018
S	AMBICA FAB. DESIGN LLP	AMBICA FAB	1019
S	KAYA CREATIVE	KAYA CR...	1020
S	SELVI ART	SELVI ART	1021
S	VRUSHTI DESIGNER	VRUSHTI D.	1022
S	ARTI FABRICS	ARTI FABR	1023
S	ABHIVADAN FASHION	ABHIVADAN	1024
S	OMKAR FASHION	OMKAR F.	1025
S	SUKHDEV TEXTILES	SUKHDEV T	1026
S	VIMARSH PRINTS	VIMARSH P.	1027
S	RADHE TEX FAB	RADHE TEXF	1028
S	SHUBH NX	SHUBH NX	1029
S	SUNDARI FASHION	SUNDARI F.	1030
S	ARCHIES CREATION	ARCHIES C	1031
S	ADINATH FASHION	ADINATH F.	1032
S	MANWER FASHION	MANWER F.	1033
S	JAIN KRANTI FAB	JAIN K.F.	1034
S	P.C.FABRICS	P.C.FABRIS	1035
S	AMAYA FASHION	AMAYA F.	1036
S	PINK FLORA CREATION	PINK FLORA	1037
S	KALA KIRTI INNOVATION	KALA KIRTI	1038
S	GAURAV INTERNATIONAL	GAURAV I.	1039
S	ANIMESH SILK MILLS P.LTD	A.S.M.P.L.	1040
S	VISHAL OVERSEAS	VISHAL OVR	1041
S	RAJ TEX  FABRICS	RAJ TEX F.	1042
S	SNEHA CREATION	SNEHA CRE	1043
S	VIJAY LAXMI FASHION	VIJAY LAX	1044
S	SAI GANGA DESIGNER	SAI GANGA	1045
S	WHATSUP CREATION	WHATSUP C	1046
S	KANU PRIYA	KANU PRIYA	1047
S	JIRAVALA TEXTILES	JIRAVALA T	1048
S	KANISHKA DESIGNER	KANISHKA D	1049
S	RAJSHRI FASHION	RAJSHRI  F	1050
S	RIDHI SIDHI TRENDZ LLP	RIDHI SIDI	1051
S	MEERA  CREATION	MEERA C.	1052
S	GUNJAN FASHION	GUNJAN F.	1053
S	VENCE SAREES	VENCE S.	1054
S	SUN STUTI CREATION	SUN STUTI	1055
S	ANIKA SAREES	ANIKA S.	1056
S	SHREYA FASHION	SHREYA F.	1057
S	HAVE MORE DESIGNER	HAVE MORE	1058
S	POOJA NX	POOJA NX	1059
S	SHREE AMILON DESIGNER	SHREE A.D.	1060
S	ADINATH DESIGNER	ADINATH D.	1061
S	GAURI FASHION	GAURI F.	1062
S	AMAYA TRENDZ	AMAYA T.	1063
S	KANHAIYA FASHION	KANHAIYA F	1064
S	PRERANA CREATION	PRERANA C	1065
S	JIRAWALA EXCLUSIVE	JIRAWALA E	1066
S	CHAKACHAK CREATION	CHAKACHAK	1067
S	VATIKA IMPEX	VATIKA IMP	1068
S	SANSKAR STUTI CREATION	SANSKAR ST	1069
S	SAI ASHA	SAI ASHA	1070
S	FEMINA CREATION	FEMINA C.	1071
S	KALA KRITI EXPRESSION	KALA K.E.	1072
S	GAURAV CREATION	GAURAV C.	1073
S	WHATSUP FABRICS	WHATSUP F.	1074
S	MANMOHAN SAREE BHANDAR	MANMOHAN	1075
S	SUNEHRI	SUNEHRI	1076
S	SHREE RAM TEX PRINT P.LTD	S.R.T.P.L.	1077
S	CORAL INDIA	CORAL INDA	1078
S	RIDHI SUMAN FABRICS	RIDHI S.F.	1079
S	VAISHNAVI CREATION	VAISHNAVI	1080
S	MADHAVAM NX	MADHAVAM	1081
S	BHAGYA SHREE DESIGNER	BHAGYA S.	1082
S	JAINAM NX	JAINAM NX	1083
S	HEER CREATION	HEER C.	1084
S	MADHAV FASHION	MADHAV F.	1086
S	DEEP MALA FASHION	DEEP MALA	1087
S	VIJAY LAXMI SILKMILLS	VIJAY L.S.	1088
S	KISHORI PRIYA	KISHORI P.	1089
S	SEEMA NX	SEEMA NX	1090
S	KASTURI TRENDZ	KASTURI T.	1091
S	SAESHA SAREE	SAESHA  S.	1092
S	PRAMUKH ART	PRAMUKH A.	1093
S	ALLOL CREATION PVT LTD	ALLOL C.P.	1094
S	SHYAM RACHNA FASHION	SHYAM R.F.	1095
S	AAMRAPALI CREATION	AAMRAPALI	1096
S	SAMBHAV SAREES (K)	SAMBHAV K	1097
S	SILK VILLA	SILK VILLA	1098
S	SAI SHLOK	SAI SHLOK	1099
S	T–3	T–3	1100
S	CORAL CREATION	CORAL C.	1101
S	BHERAV NX	BHERAV NX	1102
S	KESAR FAB	KESAR FAB	1103
S	SAMBHAV SILK	SAMBHAV SI	1104
S	SHIV SANCHI CREATION	SHIV S.C.	1105
S	KARNI TEXTILES	KARNI TEXT	1106
S	MOKSHA NX	MOKSHA NX	1107
S	MADHURAM TEXTILE	MADHURAM	1108
S	RAGHUPATI SAREES (K)	RAGHUPATI	1109
S	RATI SAREES LLP	RATI S.LLP	1110
S	NAMSHVI FASHION	NAMSHVI F.	1111
S	AKSHAT TEXTILE	AKSHAT T..	1112
S	MANJOTSAV FABRICS	MANJOTSAV	1113
S	AVIVA DESIGNER	AVIVA D.	1114
S	SHILPA DESIGNER	SHILPA D..	1115
S	KANHA CREATION	KANHA C.	1116
S	VARTIKA CREATION	VARTIKA C.	1117
S	ROOP LAXMI SAREES	ROOP LAXMI	1118
S	HEM CREATION	HEM  C..	1119
S	KALISTA INDURTRIES LLP	KALISTA I.	1120
S	GURU NANAK SILK MILLS	GURU NANAK	1122
S	NICE TEX FAB	NICE TEX F	1123
S	ARHAM CREATION	ARHAM C.	1124
S	PAL FASHION	PALFASHION	1125
S	KAMAAXI SAREES	KAMAAXI  .	1126
S	SETURI DESIGNERS	SETURI D.	1127
S	SARSWATI SAREES	SARSWATI S	1128
S	ARNAV FASHION	ARNAV F.	1129
S	KALYANI FASHION HUB	KALYANI F.	1130
S	NAMO NAVKAR TEXTILE	NAMO N.T.	1131
S	BRIJ SAREES	BRIJ SAREE	1132
S	AVENUE NX	AVENUE NX	1133
S	VIP SAREES	VIP SAREES	1134
S	T & M DESIGNER STUDIO	T & M D.S.	1135
S	VASTRA	VASTRA	1136
S	RUDRA  DESIGNER	RUDRA D.	1137
S	RANGILA CREATION	RANGILA C.	1138
S	SHELVI PRINTS	SHELVI P.	1139
S	STYLE WEL CO.	STYLE WEL	1140
S	SAI MADHAV FAB	SAI MADHAV	1141
S	SANSKAR FAB	SANSKAR F.	1142
S	NARAYANI SAREES	NARAYANI S	1143
S	ANANDAM	ANANDAM	1144
S	VARLAXMI SAREES	VARLAXMI .	1145
S	SAFFRON SAREES(K)	SAFFRON	1146
S	GANGANI SILK MILLS	GANGANI SM	1147
S	SHREE PARMESHWER SILK MILLS	S.P.S.M.	1148
S	SAJANEE SILK MILLS	SAJANEE SM	1149
S	MIGORA FASHION	MIGORA F.	1150
S	KALA KRITI	KALA KRIT	1151
S	MAHAKAL DESIGNER STUDIO	MAHAKAL D.	1153
S	D & T FASHION	D & T F.	1154
S	MAA BHAGWATI  ENTERPRISES	MAA BHAG	1155
S	SHIV CREATION	SHIV C...	1156
S	SONALI SAREES	SONALI S..	1157
S	JAY AMBEY DESIGNER	JAY AMBEY	1158
S	VANYA TRENDZ	VANYA T.	1159
S	MANISH CREATION NX	MANISH C.N	1160
S	ADITYA SYNTHETICS	ADITYA S.	1161
S	JINESHWER TEXTILE	JINESHWER	1162
S	SAGAR  DESIGNER  SAREES	SAGAR D.S.	1164
S	SHREE RAM SYNTHETICS	SHREE RAM	1165
S	SAI HARI	SAI HARI	1166
S	AAPEKSHA TEX	AAPEKSHA	1167
S	MUSKAN CREATION	MUSKAN C	1168
S	ABHIVADAN DESIGNER	ABHIVADAN	1169
S	FASHION MANTRA	FASHION M.	1170
S	MADHURAM DESIGNER	MADHURAM D	1171
S	NAARI FASHION	NAARI F.	1172
S	MAYRA SAREES	MAYRA S.	1173
S	KIRARA	KIRARA	1174
S	MANOHAR SONS	MANOHAR S	1175
S	MAHAVIR TEXTILE	MAHAVIR T.	1176
S	FASHION ATTARI	FASHION A	1177
S	NAKODA  CREATION	NAKODA C.	1178
S	KHATU SHYAM SILK MILLS LLP	K.SS.M.LLP	1180
S	YOGI SAREES	YOGI SAREE	1181
S	ETHNIC CULTUS	ETHNIC C.	1182
S	SUBH CREATION (SANSKRUTI)	SUBH C.S.	1183
S	MOTHER LAND TEX	MOTHER L.	1184
S	DHRIVA FASHION LLP	DHRIVA F..	1185
S	KAVIRA BRIDAL WEAR	KAVIRA B.W	1186
S	AKSHAR CREATION	AKSHAR C.	1187
S	HIRANGI FASHIONS	HIRANGI F.	1188
S	NANDINI SAREES LLP	NANDINI S.	1189
S	RIDVIKA SAREES	RIDVIKA S.	1190
S	RAJOSHREE DESIGNER	RAJOSHREE	1191
S	SAMBHAV FASHION	SAMBHAV F	1192
S	EKTA CREATION	EKTA C.	1193
S	VALHAREE TRENDZ	VALHAREE	1194
S	RATI SAREES	RATI SARES	1195
S	SHILP SAREES	SHILP S.	1196
S	SANSKAR TEX TRADE	SANSKAR T.	1197
S	SANSKAR TEX  PRINTS PVT LTD	S.T.P.P.L.	1198
S	SHREE BANSIWALA TRENDZ	S.B.T.	1199
S	SHREEJA FASHION	SHREEJA F.	1200
S	ARYZE	ARYZE	1201
S	NAMO NAVKAR COLLECTION	NAMO N.C.	1202
S	MAHER CREATION	MAHER C.	1203
S	JAMKUDI CHAKACHAK	JANKUDI C.	1204
S	JAMKUDI FASHION	JAMKUDI F.	1205
S	HANUMAN SILK MILLS	HANUMAN	1206
S	SAMAYRA STUDIO	SAMAYRA S	1207
S	SHREE JAGDAMBA SAREE	SHREE J.S.	1208
S	SHIV STUTI SILK MILLS	SHIV S.M	1209
S	SAMBHAV STUDIO	SAMBHAV S	1210
S	KALAKARI	KALAKARI	1211
S	KIAAN	KIAAN	1212
S	KHATUDHISH SAREES	KHATUDHISH	1213
S	UMIKA DESIGNER	UAMIKA D.	1214
S	SEJAL FASHION	SEJAL F.	1215
S	AKRUTI FASHION	AKRUTI F.	1216
S	NAVNIDHI NX	NAVNIDHI N	1217
S	NENCY ENTERPRISES	NENCY E.	1218
S	VRINDA CREATION	VRINDA C.	1219
S	SHREE LEKHA SILK MILLS	SHREE L.S.	1220
S	NUPUR COLLECTION	NUPUR C.	1221
S	SAKAMBARI SILK MILLS P.LTD	S.S.M.P.L.	1222
S	JASLEEN FASHION	JASLEEN F	1223
S	MAHEK DIVA SAREES	MAHEK D.S.	1224
S	MAHAVIR SAREES	MAHAVIR S	1225
S	ANUSHREE SAREES P.LTD	ANUSHREE	1226
S	VAISHALI PRINTS	VAISHALI P	1227
S	SHREE SHREE BALAJI FABRICS	S.S.B.F.	1228
S	SHRAVYA FASHION	SHRAVYA  F	1229
S	BABU INTERNATIONAL	BABU I.	1230
S	SUJAL FASHION	SUJAL F.	1231
S	DISU SILK MILLS	DISU S.M.	1232
S	AMKAY VASTRA BHANDAR PVT LTD	AMKAY V.B.	1233
S	M. SONS FASHION	M. SONS F.	1234
S	LAKSHMI SYNTEX	LAKSHMI	1235
S	RASHI CREATIONS	RASHI C.	1236
S	MANASI BRIDAL	MANASI B.	1237
S	LUCKY WOMEN	LUCKY W.	1238
S	SAACHI NX	SAACHI NX	1239
S	SAIYAM SAREES	SAIYAM S.	1240
S	PARVATI DESIGNER	PARVATI D	1241
S	VISHAL	VISHAL	1242
S	VIRYA FASHION	VIRYA F.	1243
S	SARIKA PRINTS	SARIKA P	1244
S	SHAKUNT WEAVES	SHAKUNT W	1245
S	SHRIWALI PRINTS	SHRIWALI P	1246
S	SAI NATH TEXTILES	SAI NATH T	1247
S	PADMAKRUTI FASHION	PADMAKRUTI	1248
S	SHREYANSH CREATION	SHREYANSH	1249
S	SHAILESH FASHION	SHAILESH F	1250
S	SHREE GURUKRUPA SAREES	SHREE G.S.	1251
S	V.RAJ SAREES	V.RAJ S.	1252
S	VIJAYA VALLABH	VIJAYA V.	1253
S	VINEET SAREES	VINEET S.	1254
S	VAAMIKA FASHION PVT LTD	VAAMIKA F.	1255
S	RAHUL FASHION PVT LTD	RAHUL F.	1256
S	RIDDHI POLY PRINTS P. LTD	R.P.P.LTD	1257
S	JEEN TEX SILK MILLS	J.T.S.M.	1258
S	OEQUAL	OEQUAL	1259
S	MONIKA TRENDZ LLP	MONIKA T.	1260
S	RAHUL INTERNATIONAL	RAHUL I.	1261
S	SWASTIK PRINTS	SWASTIK P	1262
S	MADHUVAN SAREES	MADHUVAN	1263
S	MARUDHAR MORNI	MARUDHAR	1264
S	MITANSH FASHION	MITANSH F.	1265
S	RIDDHI FASHIONS	RIDDHI F.	1266
S	SAHIL CREATION	SAHIL C.	1267
S	SEEMAYA	SEEMAYA	1268
S	SHREE GANESH KRUPA POLY C.	S.G.K.P.C.	1269
S	RITVIKA FASHION LLP	RITVIKA FL	1270
S	NIRVANA DESIGNER	NIRVANA D.	1271
S	B.FINE	B.FINE	1272
S	KANISHKA DESIGNER (K)	KANISHKA D	1273
S	KARDHAR CREATION	KARDHAR C	1274
S	NEW LOOK STUDIO	NEW LOOK	1275
S	PEHNAWA SILK MILLS	PEHNAWA	1276
S	GOPIN FASHION	GOPIN F.	1277
S	NAMAMI DESIGNER	NAMAMI D.	1278
S	VEERANSHI	VEERANSHI	1279
S	V.J. FASHION	V.J. F.	1280
S	SAMLESWARI SAREES	SAMLESWRI	1281
S	NEMI DESIGNER	NEMI D.	1282
S	PADMAVATI SAREES	PADMAVATI	1283
S	NAVKAR NX	NAVKAR NX	1284
S	ARSH SAREES	ARSH S.	1285
S	PRATISTHA	PRATISTHA	1286
S	MAMTAS	MAMTA	1287
S	AKRUTI CREATION	AKRUTI C.	1288
S	MARUTI NANDAN DESIGNER	MARUTI N.D	1289
S	KALASH FASHION	KALASH F.	1290
S	JAMKUDI CREATION	JAMKUDI C.	1291
S	NITYANGI	NITYANGI	1292
S	EARTH FABRICS	EARTH F.	1293
S	RADHIKA SILK PALACE	RADHIKA	1294
S	SHREE DHAN KUBER SAREES	SHREE D.K.	1295
S	PARIS FASHION	PARIS F.	1296
S	AKSHAR FASHION	AKSHAR F.	1297
S	AMARANATH SILK MILLS	AMARNATH	1298
S	LASHA PRINTS	LASHA P.	1299
S	ASHVI SAREES	ASHVI S.	1300
S	MAA VARDAAN SAREES	MAA VARDAN	1301
S	RICH LOOK DESIGNER	RICH LOOKD	1302
S	VAIBHAV SAREES	VAIBHAV S.	1303
S	MAHESH ENTERPRISE	MAHESH E.	1304
S	AMRUT CREATION	AMRUT C.	1305
S	AMOHA TRENDZ	AMOHA T.	1306
S	SHREE YAMUNA CREATION	SHREE Y.C.	1307
S	MATESHWARI FASHION	MATESHWARI	1308
S	ANOLA SAREES	ANOLA S.	1309
S	RANG FASHION	RANG F.	1310
S	MEGHDOOT TEXTILES PVT LTD	MEGHDOOT T	1311
S	SABURI TEXTILE	SABURI T.	1312
S	LADOO CREATION	LADOO C.	1313
S	SUR SHYAM FASHION	SUR SHYAM	1314
S	SHREE JI SAREES	SHREE JI S	1315
S	WEDDING STUDIO	WEDDING S	1316
S	LABDHI SAREES	LABDHI S.	1317
S	ARINA FASHION	ARINA F.	1318
S	GAURISHA CREATIION	GAURISHA C	1319
S	ROSHNI PRINTS	ROSHNI P.	1320
S	SHAKTI CREATION	SHAKTI C.	1321
S	SHREE KRISHNA STUDIO	SHREE K.S.	1322
S	TARANG FAB	TARANG F.	1323
S	NAINA FASHION	NAINA F.	1324
S	NANI JI CREATION	NANI JI C.	1325
S	ANTRIKSH TEXTILES	ANTRIKSH	1326
S	MAYRA	MAYRA	1327
S	PARSHVDEEP TEXTILES	PARSHVDEEP	1328
S	RIONAA FASHION	RIONAA F.	1329
S	VALAM SHREE FAB	VALAM S.F	1330
S	ANTRA KALAMKARI SAREES	ANTRA K.S.	1331
S	MAHIRAJ DESIGNER	MAHIRAJ D.	1332
S	VALLABH PRINTS	VALLABH P.	1333
S	MAGIC DESIGNER	MAGIC D.	1334
S	ANAND CREATION	ANAND C.	1335
S	LAKSH FASHION	LAKSH F.	1336
S	PUJAN ENTERPRISES	PUJAN E.	1337
S	SACHPARA FASHION	SACHPARA F	1338
S	VISHAL TRENDZ	VISHAL TRE	1339
S	ARADHNA FASHION	ARADHNA	1340
S	VEDAM SAREES	VEDAM SARS	1341
S	SAVREE SACHI STUDIO	SAVREE S.S	1342
S	SHAILJA SAREE	SHAILJA S.	1343
S	SUBHASH SAREES	SUBHASH S.	1344
S	PRIYA MILAN SAREES	PRIYA M. S	1345
S	Q.D. ART	Q.D. ART	1346
S	NAREDI CREATION	NAREDI C.	1347
S	NAREDI CREATION (K)	NAREDI (K)	1348
S	SBS MODHETHNIC FASHION	SSB M. F.	1349
S	MAYAPATI FASHION	MAYAPATI F	1350
S	RATANA JYOT FASHION	RATNA JYOT	1351
S	SHREE SHUBH LAXMI ART	SHREE SHUH	1352
S	SHREE RADHA KISHAN TEXTILE	S.R.K.T.	1353
S	BHAGYA SHREE CREATION	BHGYA S.C.	1354
S	VASTRA PITARA	VASTRA P	1355
S	VIJAY SHUBH	VIJAY S.	1356
S	KALRAV SAREES	KALRAV S	1357
S	SHREE KRISHNA STDIO ( K)	S.K.S.K	1358
S	MANVI DESIGNER	MANVI D.	1359
S	RANDEEP CREATION	RANDEEP C	1360
S	RAJ MILAN DESIGNER	RAJ MILAND	1361
S	VANIVATSALYA  FAB	VANIVATSAL	1362
S	VERSACE FASHION	VERSACE F	1363
S	V.J. (K)	V.J. (K)	1364
S	SUDANI TEXTILES	SUDANI T.	1365
S	NAYASA DESIGNER	NAYASA D.	1366
S	AALIGAN ART	AALIGAN AT	1367
S	JIYA FABRICS	JIYA FABRI	1368
S	VIYAAN FASHION	VIYANN F.	1369
S	BALRAJ SAREES	BALRAJ S.	1370
S	SAI SAREES	SAI SAREES	1371"""


def add():
    split_data = supplier_data.split("\n")

    supplier_names = [y.split("\t")[1] for y in split_data]

    suppliers = [Supplier.create_supplier(supplier, "N/A") for supplier in supplier_names]

    for elements in suppliers:
        insert_individual.insert_supplier(elements)


if __name__ == "__main__":
	add()
