import sys
sys.path.append("../")
from Indivijuval import Party
from Database import insert_individual

party_data = """P	JAGDAMBA ENTERPRISE	JAGDAMBA	1
P	SHIVAM SAREE	SHIVAM	2
P	HIRAWAT FASHION	HIRAWAT	3
P	ROOP LAXMI SAREE(HELI MANDI)	ROOP	4
P	PODDAR DESIGNERS	PODDAR	5
P	GARHA BHANDAR	G BANDAR	6
P	KRISHNGI SAREES	KRISHANGI	7
P	DEEPMALA	DEEPMALA	8
P	PALKI SAREES	PALKI	9
P	ROOP LAXMI SAREES	ROOP LAXMI	10
P	KHATTAR CLOTH EMPORIUM	KHATTAR	11
P	ARORA SAREE SELECTION PVT LTD	ARORA SARE	12
P	SAMBHAV FASHION	SAMBHAV	13
P	KRISHNA SAREE EMPORIUM	KRISHNA	14
P	KANSAL SAREE CENTER	KANSAL	15
P	ANIL KUMAR SUNIL KUMAR	ANIL KUMAR	16
P	PANKAJ SYNTHETICS	PANKAJ	17
P	DULHAN SAREES	DULHAN	18
P	SUNIL TEXTILES	SUNIL	19
P	DEEPIKA SAREE PVT LTD	DEEPIKA	20
P	HOSHIYAR SINGH SURESH CHANDRA	HOSHIYAR	21
P	RANJAN (VALSAD)	RANJAN	22
P	NANDANI CREATION	NANDANI C	24
P	JAGDISH & SONS	JAGDISH	25
P	PARICHAY FASHION	PARICHAY	26
P	BHAGWATI FASHION	BHAGWATI	27
P	VENKATESH EXCLUSIVE	VANKATESH	28
P	MAAN SAREE	MAAN SAREE	29
P	VARNIKA CREATION	VARNIKA C	30
P	VRIDHI CREATION	VRIDHI	31
P	MALHOTRA SHAWLS & SAREES	MALHOTRA	32
P	S.G.SAREE CREATIONS	S.G.CREAT	33
P	ROOP MILAN	ROOP MILAN	34
P	ELEGANCE	ELEGANCE	35
P	ARNAV SAREES	ARNAV	36
P	BHARAT STORES	BHARAT	37
P	RADHE SAREES	RADHE SARE	38
P	ANKIT TEXTILES	ANKIT TEX	39
P	SHARMA ENTERPRISES	SHARMA	40
P	HARIOM RAJ KUMAR	HARIOM	41
P	RADHIKA FAB.	RADHIKA F.	42
P	SIDHANT CREATION PVT LTD	SIDHANT	43
P	DHRUTI SAREE	DHRUTI S	44
P	ANKIT SAREE CENTRE	ANKIT SARE	45
P	HASA RAM AGENCIES	HASA RAM	46
P	SANJAY PRINTS	SANJAY	47
P	SATYAM SAREES	SATYAM S	48
P	SURUCHI SAREES	SURUCHI	49
P	GARHA BHANDAR AGENCY	GARHA BHAN	50
P	GURU NISTHA TEX TREAD P LTD	GURUNISHT	51
P	SANJEELA FASHION PVT LTD	SANJEELA	52
P	NAVYUG CLOTH HOUSE	NAVYUG	53
P	DECENT FASHION	DECENT	54
P	SHRI SHARDDHARAM SILK MILLS	SHARDARAM	55
P	SIDDARTH SAREES P LTD	SIDDARTH	56
P	TULSI EXPORT	TULSI	57
P	SAREE KENDRA	SAREE KEND	58
P	JARI SAREE CENTER	JARI SAREE	59
P	GANESHI LAL OM PRAKASH	GANESHI	60
P	SHWETA DESIGNER SAREES	SHWETA	61
P	BANARAS SAREES	BANARAS	62
P	BRIJ FASHION	BRIJ	63
P	SHREE SHARDHARAM SAREE KENDRA	S SHAR.S.K	64
P	GIRIRAJ FASHIONS	GIRIRAJ	65
P	APSARA FAB.	APSARA	66
P	HARYANA SILK & SAREES	HARYANA	67
P	JIYA CREATION	JIYA CREA	68
P	KEDAR NATH RAJIV KUMAR	KEDAR NATH	69
P	SHREE PAHARIMATA	PAHARIMATA	70
P	MONIKA SAREE PVT LTD	MONIKA S	71
P	WADHWA SAREE PVT LTD	WADHWA	72
P	PADAMCHAND PREM  CHAND	PADAMCHND	73
P	MOUR SAREE CENTER	MOUR SAREE	74
P	SURAJBHAN SUNIL KUMAR	SURAJBHAN	75
P	LIBERTY SILK	LIBERTY	76
P	MATWAL JI SAREES	MATWALJI	77
P	VEDBHUSHAN SAREE P LTD	VEDBHUSHAN	78
P	SHANTI COLLECTION PVT LTD'	SHANTI	79
P	KHUSHI CREATION	KHUSHI	80
P	LALITYAM SAREES	LALITYAM	81
P	DARSHAN LAL & SONS	DARSHAN	82
P	NEW RAJ KAMAL DESIGNER & DRESS	RAJ KAMAL;	83
P	NEERAJ TEXTILES	NEERAJ	84
P	VARDHMAN FASHIONS	VARDHMAN	85
P	KAPDA MANDIR	KAPDA	86
P	WELCOME SAREES	WELCOME	87
P	MENKA SAREE SANSAR	MENKA	88
P	NEERAJ SAREE	NEERAJ	89
P	SHANTI SILK HOUSE	SHANTI	90
P	SAI MADHAV NX	SAI MADHAV	91
P	BASAVA SILK HOUSE	BASAVA	92
P	SAI MADHAV SAREES P LTD	MADHAV SAR	93
P	NARANG FASHION	NARANG	94
P	RAJDHANI SAREE SADAN	RAJDHANI	95
P	SHREE SHARDHARAM FASHION SAREE	SHARDARAM	96
P	JAN JYOTI TEXTILES	JAN JYOTI	97
P	VIVAH FASHION	VIVAH FASH	98
P	SUNDARLAL SANJIV KUMAR JAIN	SUNDAR	99
P	SHANKAR APPARELS PVT LTD	S.A.P.L.	100
P	POONAM TEXTILES	POONAM	101
P	SHAGUN	SHAGUN	102
P	QUEEN'S EMPORIUM	QUEEN'S	103
P	KASTURI SILK PALACE	KASTURI	104
P	SHARDHA SILK PALACE	SHARDHA	105
P	SHANKAR SIMRAN FABRICS	SHANKAR	106
P	RAJIV SAREE EMPORIUM	R. S. E.	107
P	SAI TEX FAB	SAI TEX	108
P	RAM NIWAS & SONS	RAM NIWAS	109
P	SHREE SAI CREATION	SHREE SAI	110
P	R.S.MOGAL	R.S.MOGAL	111
P	RAJIV SILK & SAREES	RAJIV SILK	112
P	RADHIKA SAREES	RADHIKA	113
P	MEENAKSHI SAREE CENTER P LTD	MEENAKSHI	114
P	RAMNIVASH MANMOHAN	RAMNIVASH	115
P	SWASTI SAREES	SWASTI	116
P	SARDARJI SAREE WALA	SARDARJI	117
P	SANTLAL SYNTHETICS P. LTD	SANTLAL	118
P	SAMPAT SACHIN SAREES PVT LTD	SAMPAT	119
P	SANT LAL TEK CHAND	S L T C	120
P	SUNDARI	SUNDARI	121
P	RADHE SILK MILLS	RADHE	122
P	SHANKAR FASHION	SHANKAR F	123
P	SABRANG SAREES P LTD	SABRANG	124
P	GEETANJALI	GEETANJALI	126
P	D.C. SYNTHETICS	D .C.	127
P	MEENA BAZAR	MEENA	128
P	SHANKER SAREES	SHANKER	129
P	DEEPCHAND SHYAM SUNDAR	DEEPCHAND	130
P	SHANKAR STYLE STATION	S–3	131
P	SHAM TEX	SHAM TEX	132
P	SHRISH SAREES	SHRISH	133
P	SHRI SAREE CREATION	SHRI SAREE	134
P	SHREE TRIVENI SAREE P LTD	TRIVANI	135
P	SHRI SHYAM SAREES EMPORIUM	SHRI SHYAM	136
P	SHREE RADHE TEXTILE	RADHE	137
P	PEE TEX	PEE TEX	138
P	SHREE SHARDHARAM SYNTHETICS	SHARDHARAM	139
P	LADLI COLLECTION	LADLI	140
P	SHREE BANSIDHAR TRADING CO.	S BANSIDHR	141
P	UMESH BROTHERS	UMESH	142
P	MANCHANDA SAREE CENTER	MANCHANDA	143
P	VALLABH SAREE EMPORIUM	V .S. E.	144
P	SAI TEX FAB SAREES PVT LTD	SAI TEX FB	145
P	VAID PRAKASH HARI PRAKASH	VAID	146
P	VEDANSHI	VEDANSHI	147
P	KALA SAGAR	KALA SAGAR	148
P	SHREE GANPATI CREATION	GANPATI	149
P	PARAS SAREE	PARAS	150
P	KRISHNA SAREE	KRISHNA	151
P	ATUL SAREES	ATUL	152
P	KARUNA FASHION FAB P LTD	KARUNA	153
P	S.J.ENTERPRISES	S.J.	154
P	SHRI SHYAM CREATION	SHYAM CRE	155
P	ASHWANI SILK HOUSE	ASHWANI	156
P	SHILA COLLECTION	SHILA COLL	157
P	VARDHAMAN SAREE CENTER	VARDHAMAN	158
P	L.P.SAREES P LTD	L.P.SAREE	159
P	SURYA DESIGNER	SURYA	160
P	PUNEET KUMAR NITEEN KUMAR	PUNEET	161
P	RISHABH SAREE CENTER	RISHABH	162
P	SAKAMBARI SADI	SAKAMBARI	163
P	H.V.RAJ SAREES PVT LTD	H.V.RAJ	164
P	ROOP FASHION	ROOP FASH	165
P	MADHU SAREE EMPORIUM	MADHU	166
P	SUBH LAXMI	SUBH LAXMI	167
P	SHREE SAI FASHION	SAI FASHIO	168
P	BABURAM & SONS	BABURAM	169
P	DEEP SHEEKHA	DEEP S	170
P	KING SAREE	KING SAREE	171
P	SINDWANI SAREE	SINDWANI	172
P	R.G.CREATION	R.G.CREATN	173
P	ROOP NIKHAR FASHION PVT LTD	ROOP NIKHR	174
P	NEHA SAREE EMPORIUM	NEHA SAREE	175
P	SAMUNDER SAREE CENTER (D.K)	SAMUN D K	176
P	SINDOOR SAREE	SINDOOR	177
P	YASH SAREE	YASH	178
P	S.K.SAREES	S.K.SAREES	180
P	DIVYA COLLECTION	DIVYA	181
P	SHARADA SREE	SHARADA	182
P	KUSUM SAREES	KUSUM	183
P	SHAGUN SAREE SHOWROOM	SHAGUN SAR	184
P	RATAN MANI SAREE	RATAN MNI	185
P	NEELKAMAL SELECTIONS	NEELKAMAL	186
P	A.V.CREATION	A.V.CREATI	187
P	SHRI RAM SAREE COLLECTIONS	SHREE RAM	188
P	RAJESH SAREE	RAJESH	189
P	SUMAN SAEES	SUMAN SARE	190
P	HARISHCHAND PAVAN KUMAR	HARISHCHND	191
P	DINESH BROTHERS	DINESH BRO	192
P	DISHU SAREES	DISHU SARE	193
P	ROMI TEXTILES	ROMI TEX	194
P	MANISH DESIGNER PVT LTD	MANISH DES	195
P	MUKUT BIHARI SHARAD KUMAR	MUKUT	196
P	POOJA SAREE	POOJA SARE	197
P	MARUTI COLLECTION	MARUTI C	198
P	GIRI LAL PREMCHAND SAREE P LTD	GIRI LAL	199
P	VALLABH SAREE KENDRA	V S KENDRA	200
P	JAI SAREE EMPORIUM	JAI SAREE	201
P	MAYUR SAREE CENTER	MAYUR SAR	202
P	KUNJ BIHARI COLLECTION	KUNJBIHARI	203
P	SHIPRA SAREES	SHIPRA S	204
P	SHREE SHYAM EXCLUSIVE P LTD	SHYAM EXC	205
P	ARUN FASHION	ARUN FAS	206
P	SHRI KRISHNA SAREES	S KRISHNA	207
P	KAVITA SAREE SADAN	KAVITA S	208
P	POOJA DESIGNER PVT LTD	P DESIGNER	209
P	POORNIMA SILK PRINTS	POORNIMA	210
P	SURENDRA SAREE CENTRE	SURENDER	211
P	CHANDANI EMPORIUM	CHANDANI	212
P	SAREE MAHAL	S MAHAL	213
P	JAIN SAREE CENTER	JAIN SAREE	214
P	KANIKA FASHION	KANIKA FAS	215
P	SHILPA SAREES	SHILPA S	216
P	SAVERA DESIGNAR	SAVERA D	217
P	SANGAM SAREE	SANGAM S	218
P	AMBIKA SAREE PVT. LTD.	AMBIKA	219
P	P.P SAREES	P.P.S	220
P	RAJAN SAREE PVT. LTD.	RAJAN	221
P	RAJAN ENTERPRISES	RAJAN	222
P	SIDDHI VINAYAK SAREES PVT. LTD	SIDDHI V	223
P	MADAN LAL JAIN	MADAN LAL	224
P	MAHADEV SUIT &SAREES	MAHADEV SU	225
P	SALASAR ENTERPRISES	SALASAR EN	226
P	POOJA SAREES (UDAIPUR)	POOJA SAR	227
P	H.M. BRIDAL LAHAGA	H. M. BR.L	228
P	SHREESHTI	SHREESHTI	229
P	SHRI BANKE BIHARI SAREES P.LTD	SBBSPL	230
P	GANPATI EXCLUSIVE DESIGNER S.	G.E.D.S.	231
P	PRAGATI SAREES	PRAGATI S.	232
P	RAJENDRA TEXTILES	RAJENDRA T	233
P	SHREE AAKARSHAN	SHREE  A.	234
P	SONIYA OVERSEAS EXPORT	S.O.E.	235
P	MADAN FASHION SAREES	M.F.S.	236
P	SAREE SADAN	SAREE SADN	237
P	OM DESIGNER SAREES	O.D.S.	238
P	PALAK FASHION P.LTD	P.F.P.	239
P	BOBBY SAREE CENTER	BOBBY S	240
P	GAURAV SILKS	GAURAV S.	241
P	R.K.TEXTILE	R.K.TEXTIL	242
P	ALKA PARIDHAN(BOBBY)	ALKA PARID	243
P	RUHANI SILKS(BOBBY)	RUHANI SIL	244
P	H.R.&CO.P.LTD	H.R.&CO.	245
P	VANDANA CREATION	VANDANA C	246
P	UTSAV SAREE	UTSAV SARE	247
P	KRISHAN LAL ASHWANI KUMAR	K.L.A.K.	248
P	MAHESHWARI TEXTILES	MAHESHWARI	249
P	SURAJBHAN SANTRAM	SURAJBHAN	250
P	JUGAL KISHOR JIWAN LAL&SONS	J.K.J.L.&S	251
P	PANJAB VASTRA BHANDAR	PANJAB V.B	252
P	NARANG SAREE(NAI SARAK)	NARANG S.	253
P	ARIHANT SAREE STORE	ARIHANT	254
P	SRI MAA PURNA SAREE	SRI M.P.S.	255
P	SHIVANG SAREE	SHIVANG S.	256
P	VIMAL PRASAD JAIN&SONS	VIMAL P.	257
P	SHRI SHRADHARAM FABRICS	SHRI S.F.	258
P	MILAN SAREES	MILAN S.	259
P	JAGDISH PRASAD SAREES	JAGDISH P.	260
P	SAURABH SAREE	SAURABH S.	261
P	M.A.SAREES	M.A.SAREES	262
P	RAJSHREE CREATION P.LTD	RAJSHREE	263
P	KAPIL SAREES	KAPIL SARE	264
P	SWAMI SAREES P.LTD	SWAMI S.	265
P	JINDAL SAREES P.LTD	JINDAL S.	266
P	SHRI SHANI SYNTHETICS	SHRI SHANI	267
P	CITY KART RETAIL P.LTD	CITY KART.	268
P	KASHMIRI COLLECTION	KASHMIRI C	269
P	AMAR SAREE CENTER	AMAR SAREE	270
P	SHANKER SAREE STORE P.LTD	S.S.S.P.L.	271
P	LAAJ INTERNATIONAL	LAAJ INTER	272
P	VALLAVBH EMPORIO	VALLABH E	273
P	KARIGARI DESIGNERS	KARIGARI D	274
P	MOHIT TEXTILE	MOHIT TEX.	275
P	SOMYA SAREES	SOMYA S.	276
P	A.K. CREATION	A.K.CRE..	277
P	RAVI KUMAR SACHIN KUMAR	RAVI KU.S.	278
P	ABHINANDAN SAREE EMPORIOUM	ABHINANDAN	279
P	KASHMIRI&SONS RETAIL STORE	KASHMIRI&S	280
P	NITIN SAREES	NITIN SARE	281
P	TARUN SAREE EMPORIOUM	TARUN S. E	282
P	VARUN SELECTION P. LTD	VARUN S.P	283
P	ASHOK SAREE CENTER	ASHOK SARE	284
P	AHUJA VASTRA BHANDAR	AHUJA V.B.	285
P	GUPTA SAREE SADAN	GUPTA SARE	286
P	N.V.TEXTILES	N.V.TEX..	287
P	SUREKHA DESIGNER P.LTD	SUREKHA	288
P	AJAY SAREE	AJAY S.	289
P	NIRMAL SAREES	NIRMAL S.	290
P	GAYTRI SAREE	GAYTRI S.	291
P	A.O.COLLECTION	A.O.COLLEC	292
P	SHRI VISHPRIYA SAREES	SHRI VISH	293
P	AARADHYA OVERSEAS	AARADHYA O	294
P	SAI TRADING CO.	SAI TRADIN	295
P	B.R.TEXTILES	B.R.TEXTIE	296
P	SHIVAM EMBROIDRY	SHIVAM E.	297
P	BHAWANI TEX	BHWANI TEX	298
P	MALHOTRA SAREE SELECTION	MALHOTRA S	299
P	N.TEX	N.TEX	300
P	DHARAMPAL HARISH KUMAR	D.P.H.K.	301
P	PRAKASH SAREE BHANDAR	PRAKASH S	302
P	SWRIT SAREES	SWRIT SAR	303
P	AKSHITA CREATION	AKSHITA C.	304
P	SWEDESH KHADI TRADERSP.LTD	S.K.T.P.L.	305
P	RAJIV SAREE	RAJIV SARE	306
P	GOYAL TRADERS	GOYAL T.	307
P	DIWAN SAREES	DIWAN S.	308
P	VIVAH SAREE SADAN	VIVAH S.S.	309
P	KANISH CREATION	KANISH C.	310
P	MURALIWALA SAREES	MURALIWALA	311
P	SHRI YASH TEX FAB P.LTD	SHRI Y.T.F	312
P	PANKAJ SAREES	PANKAJ  S.	313
P	S.S. CREATION	S.S. CRE.	314
P	PRINCE SAREES	PRINCE S.	315
P	JAGAN NATH &SONS	JAGAN NATH	316
P	BOBBY SAREES	BOBBY S.	317
P	VALLABH STUDIO	VALLABH S.	318
P	HOLANI APPARELS	HOLANI A.	319
P	NANDLAL SAREES P. LTD	NAND LAL	320
P	PALAKI CREATION	PALAKI C..	321
P	A.K.RETAIL P.LTD	A.K.RETAIL	322
P	SHANKAR CREATION	SHANKAR C.	323
P	VIVAH SAREES	VIVAH S.	324
P	HARYANA SAREES	HARYANA S	325
P	LIBAS B2B	LIBAS B2B	326
P	JAY BHARAT FASHION	JAY BHARAT	327
P	RATAN LAL RAJESH KUMAR JAIN	R.L.R.K.J	328
P	VAISHNAVI TEXTILES	VAISHNAVI	329
P	DEVI EMBRODRY SAREE	DEVI E. S	330
P	SARSWATI SAREES	SARSWATI	331
P	SIDHI CREATION	SIDHI C.	332
P	ANNU SAREES	ANNU S.	333
P	N.S.SAREE	N.S.SAREE	334
P	N.M, AGRAWAL & CO	N.M. A.	335
P	FALAK SILKY LAHENGA	FALAK S.L.	336
P	SHRI AMBE TEXTILE	SHRI AMBE	337
P	SHREE SHYAM COLLECTION	SHREE S.C	338
P	SANT LAL OM PRAKASH	SANTLALOP	339
P	VALLABH SAREES (PRITAMPURA)	VALLABH S.	340
P	SAI KRUPA FASHION	S.K.F.	341
P	VC SAREES P LTD	VC SAREE	342
P	SHOBHA RAM SONS	SHOBHA	343
P	RISHABH IMPEX	RISHABH I.	344
P	BATRA EMPORIUM	BATRA E.	345
P	JAGDISH SAREE EMPORIOUM	J.S.E.	346
P	SHRINAGAR FASHION PVT LTD	SHRINAGAR	347
P	H.M.DESIGNER STUDIO	H.M.D.	348
P	VISHAL SAREES	VISHAL S.	349
P	J & K GROUP	J & K G.	350
P	SHREE SAREE EMPORIUM	SHREE S.E.	351
P	ANIL TEXTILES	ANIL TEX.	352
P	KANSAL TEX FAB	KANSAL T.F	353
P	SAHIBA FASHION	SAHIBA F.	354
P	JAIN SAREE HOUSE	JAIN SAREE	355
P	ANAIKA TRENDZ	ANAIKA T.	356
P	SHIVA SUIT & SAREES	SHIVA  S.S	357
P	SHREE KUNJ BIHARI SAREES	SHREE. K.B	358
P	ADVIKA CREATIONS	ADVIKA C.	359"""


def add():
    split_data = party_data.split("\n")

    party_names = [y.split("\t")[1] for y in split_data]

    parties = [Party.create_party(party, "N/A") for party in party_names]

    for elements in parties:
        insert_individual.insert_party(elements)

add()



